Resources:
  VPCB:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc-dev-b

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt VPCB.CidrBlock, 6, 8 ]]
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPCB
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: private-dev-b

  LambdaSecurityGroupB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Lambda Functions
      VpcId: !Ref VPCB
      Tags:
        - Key: "Name"
          Value: "LambdaSecurityGroup"
